# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(verbose_name='\u0441\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0434\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('active', models.BooleanField(default=False, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u043e')),
                ('image', models.TextField(blank=True, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': '\u0441\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0441\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('href', models.CharField(max_length=200, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430')),
                ('target', models.CharField(choices=[('EM', ''), ('BL', '_blank'), ('SF', '_self'), ('PR', '_parent'), ('TP', '_top')], default='EM', max_length=2, verbose_name='\u043a\u0430\u043a \u043e\u0442\u043a\u0440\u044b\u0442\u044c?')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u0441\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u0441\u0441\u044b\u043b\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='links',
            field=models.ManyToManyField(blank=True, to='competition.Link', verbose_name='\u0441\u0441\u044b\u043b\u043a\u0438'),
        ),
    ]
