# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='entry_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='competition',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0434\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='competition',
            name='link',
            field=models.URLField(default='#', verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0434\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430'),
        ),
        migrations.AddField(
            model_name='competition',
            name='submission_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.TextField(default='/static/img/competition-logo.svg', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='links',
            field=models.ManyToManyField(blank=True, to='competition.Link', verbose_name='\u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b'),
        ),
    ]
