# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20160515_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-finish_date', '-pub_date'], 'verbose_name': '\u0441\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u0435', 'verbose_name_plural': '\u0441\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u044f'},
        ),
    ]
