# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20160516_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 22, 13, 41, 12, 985231, tzinfo=utc), verbose_name='\u0434\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
    ]
