# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competition_upd_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-finish_date', '-pub_date'], 'verbose_name': 'competition', 'verbose_name_plural': 'competitions'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['title'], 'verbose_name': 'link', 'verbose_name_plural': 'links'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='content',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='entry_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='entry deadline'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='finish date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.TextField(default='/static/img/competition-logo.svg', verbose_name='url for logo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='link',
            field=models.URLField(default='#', verbose_name='site link'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='links',
            field=models.ManyToManyField(blank=True, to='competition.Link', verbose_name='materials'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='submission_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='submission deadline'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(max_length=200, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='link',
            name='target',
            field=models.CharField(choices=[('EM', ''), ('BL', '_blank'), ('SF', '_self'), ('PR', '_parent'), ('TP', '_top')], default='EM', max_length=2, verbose_name='target'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
