# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competition_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('article', models.URLField(verbose_name='article link')),
                ('video', models.URLField(verbose_name='video link')),
                ('slides', models.URLField(verbose_name='slides link')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['finish_date'], 'verbose_name': 'competition', 'verbose_name_plural': 'competitions'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='links',
            field=models.ManyToManyField(blank=True, to='competition.Link', verbose_name='links'),
        ),
        migrations.AddField(
            model_name='competition',
            name='materials',
            field=models.ManyToManyField(blank=True, to='competition.Material', verbose_name='materials'),
        ),
    ]
