# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20160525_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='materials',
        ),
        migrations.AddField(
            model_name='material',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competition.Competition'),
            preserve_default=False,
        ),
    ]
