# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_auto_20160525_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slides',
            field=models.FileField(blank=True, upload_to='slides', verbose_name='slides'),
        ),
    ]
