# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20160608_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='entry_deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 23, 59, 59), verbose_name='entry deadline'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 23, 59, 59), verbose_name='finish date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 0, 0), verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='submission_deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 23, 59, 59), verbose_name='submission deadline'),
        ),
    ]
