# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20160526_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.URLField(verbose_name='url for logo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='link',
            field=models.URLField(verbose_name='site link'),
        ),
    ]
