# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_auto_20160527_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='entry_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='entry deadline'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='finish date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='submission_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='submission deadline'),
        ),
    ]
